### ISSUE TITLE
😍😍😍

### ISSUE THREAD

**Issue by jbaxleyiii** [n1ru4l/apollo-link-rest#1]
This is so amazing!!! Any interest in us moving it to the apollographql org and having the apollo team help out in this?

Also I just want to say how incredibly thankful I am for people like you in the community to push the boundaries of GraphQL with such enthusiasm and vigor! People like you make our jobs so much more enjoyable and fun!

So thanks! 🤗

**Comment by n1ru4l** [comment]
Hey 😊
First of all: Thank you for apollo! It makes working with GraphQL so awesome!

At the moment this is just an experiment, whose implementation can change rapidly.

E.g. I am already have the idea from moving the directives to some client side schema that you would pass in to the link.

This could be extremly powerful. You could create definitions for existing public REST apis and share them via a schema file with other people.

Here is an example schema:

```graphql

type User {
  id: ID!
  login: String!
  friends @rest(
      route: "/users/:userId/friends"
      provides: { userId: "id" } # map id from parent object to :userId route param
  ): [User]!
}

type Query {
  user(id: ID!) @rest(route: "/users/:id", params: { id: "id" }): User
}
```

I am also okay with transferring this repository, if you like the direction I want to head into 😄

**Comment by n1ru4l** [comment]
I am going to close this since you mentioned on slack that the apollo team is going to develop their own implementation
I am going to make this repository a rest-schema builder 🤗
